#!/usr/bin/env python3
"""Text hygiene shared by the chat capture converters.

Two failures this prevents, both observed in the vault:

wikilinks — a transcript quotes ``[[ -n "$x" ]]``, ``[[:space:]]``, a CSV row, or
    a ``~/dev/memory`` note name. Written verbatim, Obsidian reads each as a
    wikilink and renders an unresolved "ghost" node, so a capture whose only
    links are quoted noise appears in the graph as a small island cluster.
    Transcript text is never a real vault edge; triage adds those afterwards.

titles — the first user message of a slash-command session is an envelope
    (``<command-message>log-app</command-message><command-name>/log-app</...``).
    Slugged, that produced filenames like
    ``...command-messagelog-appcommand-message-command-namelog-appcom...``.
"""

import re

FENCE_RE = re.compile(r"^\s*(?:```|~~~)")
# What Obsidian actually links: [[target]] closed on one line, no bracket inside.
# A bare "[[" with no closer (a truncated tool result) is literal text, not a link.
WIKILINK_RE = re.compile(r"\[\[[^\[\]\n]+\]\]")
INLINE_CODE_RE = re.compile(r"`[^`]*`")

# Envelopes Claude Code and Codex wrap around slash commands and local commands.
_ENVELOPE_TAGS = (
    "command-message", "command-name", "command-args",
    "local-command-caveat", "local-command-stdout", "local-command-stderr",
    "system-reminder", "user-prompt-submit-hook",
)
_ENVELOPE_RE = re.compile(
    r"<(" + "|".join(_ENVELOPE_TAGS) + r")>.*?</\1>",
    re.DOTALL | re.IGNORECASE,
)
_ANY_TAG_RE = re.compile(r"</?[a-zA-Z][\w-]*>")
_CAVEAT_RE = re.compile(
    r"Caveat:\s*The messages below were generated by the user while running local commands.*?"
    r"(?:unless the user explicitly asks you to\.?)",
    re.DOTALL | re.IGNORECASE,
)


def neutralize_wikilinks(text):
    """Backtick-wrap every wikilink in transcript text so it draws no graph edge.

    Inline code draws no edge in Obsidian, so the text survives byte-for-byte
    while the ghost node disappears. Fenced blocks and existing inline-code
    spans are already inert and are left untouched.
    """
    out, fenced = [], False
    for line in text.split("\n"):
        if FENCE_RE.match(line):
            fenced = not fenced
            out.append(line)
            continue
        if fenced or "[[" not in line:
            out.append(line)
            continue

        masked = INLINE_CODE_RE.sub(lambda m: " " * len(m.group(0)), line)
        pieces, cursor, rebuilt = [], 0, []
        for m in WIKILINK_RE.finditer(line):
            if masked[m.start():m.end()].strip() == "":
                continue  # already inside inline code
            pieces.append(m)
        if not pieces:
            out.append(line)
            continue
        for m in pieces:
            if m.start() < cursor:
                continue
            rebuilt.append(line[cursor:m.start()])
            rebuilt.append(f"`{m.group(0)}`")
            cursor = m.end()
        rebuilt.append(line[cursor:])
        out.append("".join(rebuilt))
    return "\n".join(out)


def strip_command_envelope(text):
    """Drop slash-command and local-command scaffolding from a user message.

    Returns "" when the message was nothing but scaffolding, which lets the
    title picker fall through to the next real message instead of slugging XML.
    """
    text = _ENVELOPE_RE.sub(" ", text or "")
    text = _CAVEAT_RE.sub(" ", text)
    text = _ANY_TAG_RE.sub(" ", text)
    # A bare "/log-app" line left on its own is a command name, not a topic.
    text = re.sub(r"^\s*/[\w-]+\s*$", " ", text, flags=re.MULTILINE)
    return re.sub(r"\s+", " ", text).strip()


# What a skill body opens with once its envelope is stripped. Slugging this
# names every /log-app capture the same thing, so the picker skips past it.
_SCAFFOLD_PREFIXES = (
    "base directory for this skill",
    "caveat:",
    "the messages below were generated",
)


def is_scaffolding(text):
    """True when the message carries no topic of its own."""
    cleaned = strip_command_envelope(text)
    if not cleaned:
        return True
    lowered = cleaned.lower()
    return any(lowered.startswith(p) for p in _SCAFFOLD_PREFIXES)


def clean_title(text, max_len=80):
    """Normalize a fallback title taken from raw message text."""
    return re.sub(r"\s+", " ", strip_command_envelope(text))[:max_len].strip()
